version: "3.8"
services:
  ports-parser:
    build: ports-parser-service
    environment:
      PORT_MANAGER_ADDR: manager:10000
    depends_on: 
      - manager
    ports:  
      - "8080:8080"
    networks:  
      - microservices
  manager:
    build: ports-manager-service
    ports: 
      - "10000:10000"
    networks: 
      - microservices     
networks: 
    microservices:       
     
     
    