version: "3"
services:
  ports-parser:
    build: ports-parser-service
    environment:
      PORT_MANAGER_ADDR: ports-manager:10000
    depends_on: 
      - ports-manager
    ports:  
      - "8080:8080"
    links: 
      - ports-manager
    networks: 
      - backend            
  ports-manager:
    build: ports-manager-service
    ports: 
      - "10000:10000"  
      
networks:
  backend:
    driver: "bridge"     
    